#!/bin/sh
# Launch River with notion-river WM.

export XKB_DEFAULT_LAYOUT=de
export XKB_DEFAULT_VARIANT=neo
export XKB_DEFAULT_MODEL=pc105
export XDG_SESSION_TYPE=wayland
export XDG_CURRENT_DESKTOP=river
export MOZ_ENABLE_WAYLAND=1
export ELECTRON_OZONE_PLATFORM_HINT=wayland
export RUST_LOG=info

exec river -c ~/.config/river/init
